name: flutter_chant_social_task
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  salomon_bottom_bar: ^3.3.2
  firebase_core: ^2.24.2
  intl: ^0.19.0
  cloud_firestore: ^4.14.0
  equatable: ^2.0.5
  flex_color_picker: ^3.5.1
  get_it: ^7.7.0
  uuid: ^4.4.2
  flutter_riverpod: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
